### ISSUE TITLE
Devices not fully loading into RebootMadDevice Status

### ISSUE THREAD

**Issue by Debaucus** [GhostTalker/RebootMadDevice#8]
```
[10-03 23:39:12.33] [           system] [              start:69  ] [C] An unhanded exception occurred!
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f73a26ae488>
    └ <Thread(RebootMadDevice, started daemon 140132476765952)>
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function install_thread_excepthook.<locals>.run_thread at 0x7f738d742488>
    └ <Thread(RebootMadDevice, started daemon 140132476765952)>

> File "start.py", line 63, in run_thread
    run_thread_old(*args, **kwargs)
    │               │       └ {}
    │               └ (<Thread(RebootMadDevice, started daemon 140132476765952)>,)
    └ <function Thread.run at 0x7f73a26ae268>

  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │             │             └ <Thread(RebootMadDevice, started daemon 140132476765952)>
    │             └ <Thread(RebootMadDevice, started daemon 140132476765952)>
    └ <Thread(RebootMadDevice, started daemon 140132476765952)>

  File "/home/***/MAD/MAD/plugins/RebootMadDevice/RebootMadDevice.py", line 171, in rmdStatusChecker
    data_plus_sleep = last_proto_data + sleep_time
                      │                 └ 0
                      └ None

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

Checking logs, all my devices are detected on first bootup. After that I wait the time frame for them to begin appearing, after 20/63 this error seems to occour? 

Error is repeatable and consistant with MAD restarts and apply settings as shown above. Not an expert on how to tackle the issue however.

**Comment by Debaucus** [comment]
Additionally, during logs I have this happening. The box first in the checker is not the first box appearing when it begins checks.

```
[10-03 23:39:11.50] [           system] [    RebootMadDevice:158 ] [D] rmdStatusChecker: {'origin_status': {'BOX1': {'injection_status': True, 'latest_data': 1633304341, 'mode_value': {'timestamp': 1633304299.8818693, 'values': $
[10-03 23:39:11.51] [        ***] [SerializedMitmDataProcessor:65  ] [I] Processing GMO. Received at 2021-10-03 23:37:35
[10-03 23:39:11.54] [           system] [    RebootMadDevice:186 ] [D] rmdStatusChecker - device: NOT_BOX1
```

**Comment by Debaucus** [comment]
My solution:

`MAD_Plugin/RebootMadDevice.py` line 171

```
data_plus_sleep = last_proto_data + sleep_time
```

Based on Googling I have added this in place in order for all devices to load in. I am unsure of the consequences of this, no error handling, but I am also no expert.

```
data_plus_sleep = last_proto_data or 0 + sleep_time
```

I am unsure what is passing 'None' data to this as other users of MadRebootDevice would likely have reported this by now if it was a reasonably common occourance.
